### ISSUE TITLE
The domain doesn't appear to be valid.

### ISSUE THREAD

**Issue by msgoff** [savonet/ocaml-alsa#2]
http://liquidsoap.fm/

**Comment by smimram** [comment]
Yes, it has been changed to https://www.liquidsoap.info/ quite some time ago. Where did you see a reference to it?

**Comment by msgoff** [comment]
It's on the main GitHub page, in the about section.

https://github.com/savonet/ocaml-alsa  
     OCaml ALSA bindings. http://liquidsoap.fm/  

The project looks interesting.  
Thank you for responding.

**Comment by smimram** [comment]
Thanks, this is now corrected.
